aws_region = "us-east-1"

kinesis_stream_name = "stock-stream"
dynamo_table_name = "stock-table"
push_to_kinesis_lambda_name = "push-to-kinesis"
process_stock_data_lambda_name = "process-stock-data"
trigger_training_job_lambda_name = "trigger-training-job"
sagemaker_model_name = "stock-prediction"
sagemaker_endpoint_name = "stock-prediction-endpoint"
ticker_symbol = "TSLA"
bucket_name = "kevinw-p2"